version: "3.8"
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    env_file: .env
    ports:
      - "27017:27017"
    restart: unless-stopped
    command: mongod
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongodb_data_container:/data/db
      - "./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js"

  tindev:
    container_name: tindev
    env_file: .env
    image: node:14-alpine
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn start
    depends_on:
      - mongo
    ports:
      - "7200:7200"
    restart: unless-stopped
    environment:
      WAIT_HOST: mongo:27017

volumes:
  mongodb_data_container:
