version: "3.8"
services:
  app:
    container_name: tindevapp
    env_file: .env
    image: node:14-alpine
    hostname: tindev
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn start
    depends_on:
      - mongodb
    ports:
      - "7200:7200"
    restart: unless-stopped

  mongodb:
    container_name: mongodb
    image: mongo:latest
    hostname: mongo
    env_file: .env
    ports:
      - "27017:27017"
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
    #   MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    restart: unless-stopped
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
