version: "3.8"
services:
  mongo:
    container_name: mongodb
    image: mongo:latest
    env_file: .env
    ports:
      - "27017:27017"
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
    #   MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    restart: unless-stopped
    volumes:
      - mongodb_data_container:/data/db

  app:
    container_name: tindev
    env_file: .env
    image: node:14-alpine
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn start
    depends_on:
      - mongo
    ports:
      - "7200:7200"
    restart: unless-stopped
    environment:
      WAIT_HOST: mongo:27017

volumes:
  mongodb_data_container:
