version: "3.8"
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    env_file: production.env
    ports:
      - "27017:27017"
    restart: unless-stopped
    command: mongod
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongodb_data:/data/db
      - "./mongo-authentication.js:/docker-entrypoint-initdb.d/db-init.js"

  tindev:
    container_name: tindev
    # image: krysyx/tindev:1.0
    image: node:14-alpine
    build:
      context: .
      dockerfile: Dockerfile
    command: [sh, -c, "/wait && yarn build"]
    depends_on:
      - mongo
    ports:
      - "7200:7200"
    restart: unless-stopped
    environment:
      WAIT_HOSTS: mongo:27017

volumes:
  mongodb_data:
